### ISSUE TITLE
Create team page

### ISSUE THREAD

**Issue by bawalsh** [Idrian/COS-301-Team-Lisp#1]
- Link to each member's social profile (e.g. GitHub, LinkedIn)
- Link to GitHub repo
- Add final deliverable link in PDF format

**Comment by hjvandermerwe** [comment]
I have created a team page. It is not much but it has all the basic elements on it. If you want to change something please do. The only things I still need is the links to everyone's accounts and I also need the link to the final pdf but this can be added later
